### ISSUE TITLE
Doesn't generate tests in addon project

### ISSUE THREAD

**Issue by kellyselden** [dfreeman/ember-css-modules-reporter#11]
I moved the dependency to `dependencies`, now it started logging to console, but still not generating tests. I tried forcing `generateTests` to true, but didn't work.

**Comment by dfreeman** [comment]
Ok, this was all getting too hairy to try and solve without actual first-class support in ECM. I made some updates to the plugin registry there such that plugins that opt in via a keyword will activate for an addon with `isDevelopingAddon() => true` even if they're only available in the host app (which is basically the status quo for how things like `ember-cli-eslint` work).

I also made some updates in this repo specifically so that we manage the reporter instances globally and produce a single lint tree, which _should_ also solve the issues you were working around before with in-repo engines.

With this, you should be able to list ecm-reporter and ecm-stylelint as `devDependencies`, and you should properly get failing tests for both app and addon linter violations.

When you have the chance, would you mind giving the new setup a try off the branches before I cut new releases of everything?

https://github.com/salsify/ember-css-modules/tree/lint-plugins
https://github.com/dfreeman/ember-css-modules-reporter/tree/lint-plugin
https://github.com/dfreeman/ember-css-modules-stylelint/tree/lint-plugin

**Comment by kellyselden** [comment]
Everything works as expected with those branches in devDependencies. Nice work!

**Comment by dfreeman** [comment]
Should be all set with `ember-css-modules@0.7.6` and `ember-css-modules-reporter@1.2.0`!
